/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Query } from './query';

/**
 * 
 * @export
 * @interface ADRQuery
 */
export interface ADRQuery {
    /**
     * Unit output for the system. This maybe IMPERIAL or METRIC or DEFAULT. All units that can be converted will be converted
     * @type {string}
     * @memberof ADRQuery
     */
    'unitOutput'?: UnitOutput;
    /**
     * The query that is be executed. It can be made up of multiple individual queries, combined with AND or OR
     * @type {Array<Query>}
     * @memberof ADRQuery
     */
    'queries'?: Array<Query>;
}

export const UnitOutput = {
    Imperial: 'IMPERIAL',
    Metric: 'METRIC',
    Default: 'DEFAULT'
} as const;

export type UnitOutput = typeof UnitOutput[keyof typeof UnitOutput];


