/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This class represents a mathematical formula for performing calculations. Only one of leftOperand, leftOperandValue, or leftOperandFormula should be set. Only one of rightOperand, rightOperandValue, or rightOperandFormula should be set. Operation is required.
 * @export
 * @interface Formula
 */
export interface Formula {
    /**
     * The name of the formula, this will be used as the CSC Header.
     * @type {string}
     * @memberof Formula
     */
    'name'?: string;
    /**
     * The left operand of the formula. Only one of leftOperand, leftOperandValue, or leftOperandFormula should be set.
     * @type {string}
     * @memberof Formula
     */
    'leftOperand'?: string;
    /**
     * The right operand of the formula. Only one of rightOperand, rightOperandValue, or rightOperandFormula should be set.
     * @type {string}
     * @memberof Formula
     */
    'rightOperand'?: string;
    /**
     * The value of the left operand in the formula. Only one of leftOperand, leftOperandValue, or leftOperandFormula should be set.
     * @type {number}
     * @memberof Formula
     */
    'leftOperandValue'?: number;
    /**
     * The value of the right operand in the formula. Only one of rightOperand, rightOperandValue, or rightOperandFormula should be set.
     * @type {number}
     * @memberof Formula
     */
    'rightOperandValue'?: number;
    /**
     * 
     * @type {Formula}
     * @memberof Formula
     */
    'leftOperandFormula'?: Formula;
    /**
     * 
     * @type {Formula}
     * @memberof Formula
     */
    'rightOperandFormula'?: Formula;
    /**
     * The unit of measurement for the left operand in the formula.
     * @type {string}
     * @memberof Formula
     */
    'leftOperandUnit'?: string;
    /**
     * The unit of measurement for the right operand in the formula.
     * @type {string}
     * @memberof Formula
     */
    'rightOperandUnit'?: string;
    /**
     * The operation to be performed in the formula. Required.
     * @type {string}
     * @memberof Formula
     */
    'operation'?: Operation;
}

export const Operation = {
    Multiply: 'MULTIPLY',
    Divide: 'DIVIDE',
    Add: 'ADD',
    Subtract: 'SUBTRACT',
    Modulo: 'MODULO',
    Power: 'POWER'
} as const;

export type Operation = typeof Operation[keyof typeof Operation];


