/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TinkarConceptModel
 */
export interface TinkarConceptModel {
    /**
     * 
     * @type {number}
     * @memberof TinkarConceptModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TinkarConceptModel
     */
    'conceptId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TinkarConceptModel
     */
    'conceptName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TinkarConceptModel
     */
    'conceptDescription'?: string;
}

